displayName=Healthy Stray Varrock Dogs
author=UnCorny
description=Cosmetically makes Varrock's stray dogs and Duke appear healthy.
tags=dog,dogs,varrock,duke,cosmetic
plugins=com.cornydonkeh.healthydogs.HealthyDogsPlugin
version=3
build=standard
